export * from './product'
export * from './filter'
export * from '../../features/detail-features/mockup/slider'
export * from './detail'
export * from './breadcrumbs'
export * from './social-list'
export * from '../../features/home-features/mockup/brands'
export * from '../../features/home-features/mockup/news'